# properties 버전
# 속성 계층을 마침표로 해서
# spring.application.name=ex07_mybatis

# YML버전
#계층 구조를 콜론으로 함 (들여쓰기를 한다.정확하게 들여쓰기를 해야 함 'space*2')
#반드시 콜론 다음에는 공백이 1개 있어야 한다 (붙여 쓰면 안됨)
spring:
  application:
    name: ex07_mybatis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_db?serverTimezone=Asia/Seoul
    username: root
    password: P@ssw0rd

  sql:
    init:
      mode: always #앱 구동시 초기 스크립트(schema.sql,data.sql) 항상(자동) 실행
mybatis:
  configuration:
    map-underscore-to-camel-case: true # user_id -> userId
  type-aliases-package: com.example.mybatis.domain
  mapper-locations: classpath:mapper/*.xml
